
DROP DATABASE IF EXISTS `PlayFitBD`;

CREATE DATABASE `PlayFitBD`;
USE `PlayFitBD`;

CREATE TABLE usuarios (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nombre` VARCHAR(100) NOT NULL,
    `apellido` VARCHAR(100) NOT NULL,
    `correo` VARCHAR(150) NOT NULL UNIQUE,
    `contrasena` VARCHAR(255) NOT NULL,
    `imagenPerfil` VARCHAR(255) NOT NULL
);